name: rotten_potatoes
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  http: ^0.12.1
  auto_size_text: ^2.1.0
  fluttertoast: ^4.0.1
  shared_preferences: ^0.5.7+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/ProximaNova-Regular.otf
        - asset: assets/fonts/ProximaNova-Bold.otf
  
  assets:
    - assets/images/